django101/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',       include('social.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.conf.urls import include, url
from social import views

urlpatterns = [
    url(r'login/', views.social_login, name='login'),
    url(r'$^',     views.index, name='index'),
    url(r'home/', views.home, name='home'),
    url(r'post/add/', views.add_post, name="add_post"),
    url(r'comment/add/', views.add_comment, name='add_comment'),
    url(r'post/delete/(?P<post_id>[0-9]+)/$',   views.delete_post, name="delete_post"),
	url(r'sign_up/', views.sign_up, name='sign_up'),
	url(r'user/add_user', views.add_user, name='add_user'),
	url(r'bubble/', views.bubble, name="bubble"),
    url(r'bubble2/', views.bubble2, name="bubble2"),
]

social/models.py
from __future__ import unicode_literals

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
#from django.contrib.auth.forms import UserCreationForm

# Create your models here.

class Post(models.Model):
    text = models.TextField()
    poster = models.ForeignKey(User)
    date_time = models.DateTimeField(auto_now=True)
    photo = models.ImageField(null=True, blank=True)

class Comment(models.Model):
    text = models.TextField()
    poster = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    date_time = models.DateTimeField(auto_now=True) 
    
    class Meta:
        ordering = ['-date_time']

social/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, HttpResponseForbidden
from django.core.urlresolvers import reverse
from social.models import Post, Comment, User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from social.models import Comment, Post # put this at the top with the other imports

# Create your views here.

def index(request):
    return render(request, 'social/index.html')
    
def social_login(request):
   check = _check_post_request(request, ['username', 'password'])
   if check[0]:
       user = authenticate(username=request.POST['username'], password=request.POST['password']) 
       if user is not None:
           login(request, user)
           return HttpResponseRedirect(reverse('social:home'))
       else:
           return HttpResponseBadRequest("The combination of username and password does not exist.")
   else:
       return HttpResponseBadRequest(check[1])

@login_required
def home(request):
    if request.method == 'GET':
        posts = Post.objects.all()
    elif request.method == 'POST':
        check = _check_post_request(request, ['search_terms'])
        if check[0]:
            search_term = request.POST['search_terms']
            posts = Post.objects.filter(text__icontains=search_term)
        else:
            return HttpResponseBadRequest(check[1])
    posts = posts.order_by('-date_time')
    return render(request, 'social/home.html', {'posts': posts, 'user': request.user})

def add_user(request):
    check = _check_post_request(request, ['username', 'password'])
    errorMsg = ""
    if check[0]:
        if User.objects.filter(username = request.POST['username']).exists():
            errorMsg = "This username is already in use!"
            return render(request, 'social/sign_up.html', {'error': errorMsg})
        try:
            validate_password(request.POST['password'])
        except ValidationError as error:
            errorMsg = str(error)    
            return render(request, 'social/sign_up.html', {'error': errorMsg})
        #new_user = User()
        #new_user.username = request.POST['username']
        #new_user.password = request.POST['password']
        new_user = User.objects.create_user(request.POST['username'], '', request.POST['password'])
        new_user.save()
        return render(request, 'social/index.html')    
    else:
        return HttpResponseBadRequest(check[1])

def sign_up(request):
    return render(request, 'social/sign_up.html')

@login_required
def add_post(request):
    check = _check_post_request(request, ['text'])
    if check[0]:
        new_post = Post()
        new_post.text = request.POST['text']
        new_post.poster = request.user
        if 'photo' in request.FILES and request.FILES['photo'] is not None:
            new_post.photo = request.FILES['photo']
        new_post.save()
        #save_to_csv(request)
        return HttpResponseRedirect(reverse('social:home'))
    else:
        return HttpResponseBadRequest(check[1])

def _check_post_request(request, keys):
    if request.method != 'POST':
        return (False, "This method should be called with a POST method!")
    for key in keys:
        if key not in request.POST:
            return (False, "The POST request should contain a {} field".format(key))
        if not request.POST[key]:
            return (False, "The {} field cannot be empty!".format(key))
    return (True, "Everything is alright!")
        
def _check_post_request(request, keys):
    # Check that the request method is POST
    if request.method != 'POST':
        return (False, "This method should be called with a POST method!")
    for key in keys:
        # Check that the key exists
        if key not in request.POST:
            return (False, "The POST request should contain a {} field".format(key))
        # Check that the text is not empty
        if not request.POST[key]:
            return (False, "The {} field cannot be empty!".format(key))

    return (True, "Everything is alright!")
	
def bubble(request):
	return render(request, 'social/bubble.html')

def bubble2(request):
    return render(request, 'social/bubble2.html')
    
@login_required
def add_comment(request):
    check = _check_post_request(request, ['comment', 'post_id'])
    if check[0]:
        new_comment = Comment()
        new_comment.poster = request.user 
        new_comment.text = request.POST['comment']
        try:
            post = Post.objects.get(pk=request.POST['post_id'])
            new_comment.post = post
        except Post.DoesNotExist:
            return HttpResponseBadRequest("There is no Post with id {}".format(request.POST['post_id']))
        new_comment.save()
        return HttpResponseRedirect(reverse('social:home'))
    else:
        return HttpResponseBadRequest(check[1])
        
@login_required
def delete_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    if request.user != post.poster:
        return HttpResponseForbidden("You can only delete your own posts!")
    else:
        post.delete()
        return HttpResponseRedirect(reverse('social:home'))

social/templates/social/bubble.html
<html>
  <head>
    {% load staticfiles %}
    <title> The Network Institute bubble chart! </title>
	
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>
  </head>
  <body>
     <h3 style="text-align: center;">Sentiment analysis on posts, feel free to hover over any bubbles or <a href="{% url 'social:home' %}">return to the home page</a></h3>
	<script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'social/twitter.js' %}"></script>
  </body>
</html>

social/templates/social/bubble2.html
<html>
  <head>
    {% load staticfiles %}
    <title> The Network Institute bubble chart! </title>
	
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>
  </head>
  <body>
     <h3 style="text-align: center;">Sentiment analysis on posts, feel free to hover over any bubbles or <a href="{% url 'social:home' %}">return to the home page</a></h3>
	<script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'social/bubbleNew.js' %}"></script>
  </body>
</html>

social/templates/social/home.html
<html>
  <head>
    {% load staticfiles %}
    <title> The Network Institute forum! </title>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>
<style>
.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}
</style>
  </head>
  <body>
    <div class='container'>
	<div class='row' id='lineChartContainer'><h3 style='text-align: center;'>How often was something posted?</h3></div>
<div class='row'>
  <!-- New post container -->
  <div class='col-xs-8 col-xs-offset-2'>
    <div class='panel panel-primary' id='new-post'>
      <div class='panel-body'>
	  	<h1> 	Welcome! </h1>
	<p> 
This website contains a forum about project from the Network Institute. Feel free to look around!
</p><p>
This website contains a forum about projects from the Network Institute. Feel free to look around!
To give you some guidance, below you can post a comment and optionally add an image to it. Use a hashtag (#) to indicate the project you are talking about (all projects of the Network Institute are listed on the right of the page, you can click on it for more information). The sentiment of the post about the project is visualized in a bubble chart. You can also introduce a new project! By introducing the projectname with an asterisk (e.g. *newidea) you can indicate that your post is about a new project. The sentiment bubbles of the new projects are shown in a different graph where all new projects are introduced. With this graph the sentiment per project can be analyzed. Another feature that is included in the website is the timeline (which can be seen above). This timeline indicates how popular the site is by showing how many posts have been posted on a day, so make sure you jack up the number!
	</p>
	<a class='btn btn-success' href="{% url 'social:bubble' %}">Show bubble chart existing projects</a>
	<a class='btn btn-success' href="{% url 'social:bubble2' %}">Show bubble chart new projects</a>
        <h1> Write a new post </h1>
		<h3> Use a hashtag (#) before the project name to indicate you are talking about the project. Use a asterisk (*) before the project name to indicate you are talking about an new project. Also use these indications in the comments. Otherwise, the comment will not be included in the sentiment analysis. </h3>
        <form action="{% url 'social:add_post' %}" method="post" id='new-post-form' enctype='multipart/form-data'>
        {% csrf_token %}
          <div class='form-group'>
            <textarea class='form-control'name='text' form='new-post-form' required placeholder="Write your post here..."></textarea> 
          </div>
          <div class='form-group'>
            <input id='photo-upload' class='form-control' 
                   type='file' name='photo' accept='image/*'>
            </input>
            <label for='photo-upload'>Upload a photo</label>
          </div>
          <button type='submit' class='btn btn-default'>Post</button>
        </form>
      </div>
    </div>
  </div>

  <!-- Search box -->
  <div class='col-xs-2'>
    <div class='well'>
      <form action="{% url 'social:home' %}" method="post" id='search-bar'>
        {% csrf_token %}
        <div class='form-group'>
          <input type='text' class='form-control' name='search_terms' required placeholder='Search in posts...'>
        </div>
        <button type='submit' class='btn btn-primary'>Search</button>
      </form>
      <a class='btn btn-success' href="{% url 'social:home' %}">Show all</a>
    </div>
	</div>

		        <div class='col-xs-8 col-xs-offset-2'>
          {% for post in posts %}
          <div class='panel panel-default' id="{{post.id}}">
            <div class='panel-heading'>
  <h4>{{post.poster.username}}</h4>
  <h4 class='small'>
    posted on {{post.date_time}}
    {% if post.poster == user %}
    <form action="{% url 'social:delete_post' post.id %}" method="post" id='delete-post'>
      {% csrf_token %}
      <button type='submit'title='delete post' class='glyphicon glyphicon-trash pull-right'></button>
    </form>
    {% endif %}
  </h4>
</div>
<div class='panel-body'>
  <p class='lead'>{{post.text}}</p>
</div>
{% if post.photo %}
<div class='col-xs-10 col-xs-offset-1'>
  <img class='img-responsive center-block img-rounded' src={{post.photo.url}}/>
</div>
{% endif %}
            <div class='row'>
              <div class='col-xs-10 col-xs-offset-1'>
                <ul class='list-group'>
                  {% for comment in post.comment_set.all %}
                  <li class='list-group-item'> 
                    {{comment.text}} - {{comment.poster.username}} ({{comment.date_time}}) 
                  </li>
                  {% endfor %}
                </ul>
                <form action="{% url 'social:add_comment' %}" method="post">
                {% csrf_token %}
                  <div class='form-group'>
                    <input class='form-control' type='text' name='comment' required placeholder="Write your comment here..."/>
                  </div>
                  <input type='hidden' name='post_id' value={{post.id}} />
                  <button class='btn btn-default' type='submit'>Submit</button>
                </form>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      
	
	<!-- Added: list of hashtags-->
	<div class='col-xs-2'>
		<p>The following list shows the hashtags that can be used to link a post with a project of the Network Institute.
		Clicking on the hashtag (if underlined) will show the project description.</p>
		<ul> 
		<li><a href="http://research-acumen.eu/" target="_blank">#ACUMEN</a></li>
		<li><a href="http://agora.cs.vu.nl/" target="_blank">#Agora</a></li>
		<li><a href="http://disastergovernance.info/" target="_blank">#area</a></li>
		<li><a href="https://www.esciencecenter.nl/" target="_blank">#BiographyNed</a></li>
		<li><a href="http://www.ehumanities.nl/computational-humanities/ceda_r/" target="_blank">#CEDA_R</a></li>
		<li><a href="http://chip.win.tue.nl/home.html" target="_blank">#CHIP</a></li>
		<li><a href="http://www.conpaas.eu/" target="_blank">#ConPaaS</a></li>
		<li><a href="http://www.cltl.nl/projects/previous-projects/cornetto/" target="_blank">#Cornetto</a></li>
		<li>#Cyberchondria</li>
		<li><a href="http://www.data2semantics.org/" target="_blank">#Data2Semantics</a></li>
		<li>#Depression</li>
		<li><a href="http://worldwidesemanticweb.org/" target="_blank">#DownscalingSW</a></li>
		<li><a href="http://www.cltl.nl/projects/previous-projects/dutchsemcor/" target="_blank">#DutchSemCor</a></li>
		<li>#DutchShips&amp;Seamen</li>
		<li><a href="http://ecomeu.info/" target="_blank">#EcomEU</a></li>
		<li><a href="http://www.ehumanities.nl/computational-humanities/elite-network-shifts/" target="_blank">#EliteNetworkShifts</a></li>
		<li><a href="http://eurecaproject.eu/" target="_blank">#Eureca</a></li>
		<li>#EWiDS</li>
		<li><a href="https://worldplantage.wordpress.com/" target="_blank">#Foroba Blo</a></li>
		<li>#GLAMMap</li>
		<li><a href="http://globalwordnet.org/" target="_blank">#GlobalWorldNet</a></li>
		<li>#GreenICTpractices</li>
		<li><a href="http://kyoto-project.eu/xmlgroup.iit.cnr.it/kyoto/index.html" target="_blank">#KYOTOProject</a></li>
		<li><a href="http://ldbcouncil.org/industry/organization/origins" target="_blank">#LDBC</a></li>
		<li>#MCSD</li>
		<li>#MechanismsLinguisticBias</li>
		<li>#METIS</li>
		<li><a href="http://www.minix3.org/" target="_blank">#Minix3</a></li>
		<li><a href="https://monaproject.wordpress.com/" target="_blank">#MONA</a></li>
		<li><a href="http://amsterdamgesturecenter.com/members/" target="_blank">#MSLCG</a></li>
		<li><a href="http://www.nessi-europe.com/default.aspx?page=home" target="_blank">#NESSI</a></li>
		<li><a href="http://www.internet-science.eu/" target="_blank">#NetworkExcellenceInternetScience</a></li>
		<li><a href="http://www.newsreader-project.eu/" target="_blank">#NewsReader</a></li>
		<li><a href="http://notube.tv/" target="_blank">#NoTube</a></li>
		<li><a href="http://www.opener-project.eu/" target="_blank">#OpeNER</a></li>
		<li><a href="http://www.openphacts.org/" target="_blank">#OpenPhacts</a></li>
		<li>#@PhilosTEI</li>
		<li><a href="http://www.prestoprime.org/" target="_blank">#PrestoPRIME</a></li>
		<li><a href="http://www.ehumanities.nl/computational-humanities/the-riddle-of-literary-quality/" target="_blank">#RiddleLiteraryQuality</a></li>
		<li><a href="http://www.commit-nl.nl/projects/socially-enriched-access-to-linked-cultural-media/" target="_blank">#SEALINCMEDIA</a></li>
		<li><a href="http://selemca.camera-vu.nl/projects/selemca.html" target="_blank">#Selemca</a></li>
		<li>#SemanticsHistory</li>
		<li><a href="http://sina.birzeit.edu/SIERA/" target="_blank">#Siera</a></li>
		<li><a href="http://stress.few.vu.nl/" target="_blank">#STRESS</a></li>
		<li>#SPREAD</li>
		<li>#Text2Politics</li>
		<li>#FromText2PoliticalPositions</li>
		<li><a href="http://www.fsw.vu.nl/nl/onderzoek/onderzoeksprogrammas/organisatiewetenschappen/tracking-networks-of-communications/index.aspx" target="_blank">#TrackingNetworksCommunication</a></li>
		<li><a href="http://www.networkinstitute.org/academy-assistants/aaprojects2012/transcending-or-confining/" target="_blank">#TranscendingConfining</a></li>
		<li><a href="http://www.ehumanities.nl/computational-humanities/tunes-tales/" target="_blank">#Tunes&amp;Tales </a></li>
		<li>#ValueIT</li>
		<li>#VerrijktKoninkrijk</li>
		<li><a href="http://www.metaphorlab.org/&quot;&quot;" target="_blank">#VISMET</a></li>
		<li><a href="http://vista-tv.eu/" target="_blank">#ViSTA-TV</a></li>
		<li><a href="http://mvoices.eu/" target="_blank">#VOICES</a></li>
		<li><a href="http://w4ra.org/" target="_blank">#W4RA</a></li>
		<li><a href="https://www.digivaardigdigiveilig.nl/" target="_blank">#WomenICT</a></li>
		</ul>
  </div></div>

	<script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'social/time.js' %}"></script>
  </body>
</html>

social/templates/social/index.html
<html>
  <head>
    {% load staticfiles %}
    <title> The Network Institute forum! </title>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>
  </head>
  <body role='document'>
    <div class="container">
      <div class='jumbotron'>
        <h1> Welcome to the forum about the Network Institute!</h1>
      </div>
      <div class='row'>
        <div class='col-xs-8 panel panel-default'>
          <div class='panel-body'>
            <p> On this forum, you can give your opinion about the projects of the Network Institute. On this site you can track how many people are posting. 
			Also, a sentiment analysis is performed on these posts. What project is the most populair on this moment?
            </p>
          </div>
        </div>
        <div class='col-xs-4'>
          <h2> Please sign in to continue </h2>

          <form action="{% url 'social:login' %}" method="post">
            {% csrf_token %}
            <div class='form-group'>
              <label for="username-input">Username</label>
              <input type="text" class="form-control" required name="username" id="username-input"> 
            </div>
            <div class='form-group'>
              <label for="password-input">Password</label>
              <input type="password"  class="form-control"  required name="password" id="password-input"> 
            </div>
            <button type="submit" class="btn btn-primary">Log in</button>
			<a href="{% url 'social:sign_up' %}" > Or register here!</a>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

social/templates/social/sign_up.html
<html>
  <head>
    {% load staticfiles %}
    <title> Social </title>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>

  </head>
  <body>
	<div class="container">
		<div class='col-xs-6 col-xs-offset-3'>
			<div class="panel panel-primary" id='new-user'>
			<h1> Create a new account!</h1>
			{% if error != "" %}
				<p>
				{{error}}
				</p>
			{% endif %}
			<form action="{% url 'social:add_user' %}" method="post" id='new-user-form'>
			{%csrf_token %}
				<div class='form-group'>
					<label for="username-input">Username</label>
					<input type='text' class='form-control' required name='username' id='username-input'>
				</div>	
				<div class='form-group'>
					<label for="password-input">Password</label>
					<input type='password' class='form-control' required name='password' id='password-input'>
				</div>
				<button type="submit" class="btn btn-primary">Sign up</button>				
			</div>
		</div>
	</div> 
  
  </body>
  </html>